name: FCI
version: 1.0
author: HappyHappyBoy & FilipZocktan

main: de.teamfci.main.main
commands:
  getitem:
    description: Get An Random Item Dropped From Monsters
  fci:
    description: FCI Main Command